# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewOpcao.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewOpcao(object):
    def setupUi(self, ViewOpcao):
        ViewOpcao.setObjectName("ViewOpcao")
        ViewOpcao.resize(405, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewOpcao.sizePolicy().hasHeightForWidth())
        ViewOpcao.setSizePolicy(sizePolicy)
        ViewOpcao.setMinimumSize(QtCore.QSize(405, 324))
        ViewOpcao.setMaximumSize(QtCore.QSize(405, 324))
        ViewOpcao.setBaseSize(QtCore.QSize(405, 324))
        self.centralwidget = QtWidgets.QWidget(ViewOpcao)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setObjectName("btnSair")
        self.horizontalLayout_2.addWidget(self.btnSair)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btnSimulacoes = QtWidgets.QPushButton(self.centralwidget)
        self.btnSimulacoes.setObjectName("btnSimulacoes")
        self.horizontalLayout.addWidget(self.btnSimulacoes)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnNaoSimular = QtWidgets.QPushButton(self.centralwidget)
        self.btnNaoSimular.setObjectName("btnNaoSimular")
        self.horizontalLayout.addWidget(self.btnNaoSimular)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem7, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 9, 1, 1, 1)
        ViewOpcao.setCentralWidget(self.centralwidget)

        self.retranslateUi(ViewOpcao)
        QtCore.QMetaObject.connectSlotsByName(ViewOpcao)

    def retranslateUi(self, ViewOpcao):
        _translate = QtCore.QCoreApplication.translate
        ViewOpcao.setWindowTitle(_translate("ViewOpcao", "SysInventFlor - Escolha Inicial"))
        self.btnSair.setText(_translate("ViewOpcao", "Sair"))
        self.label.setText(_translate("ViewOpcao", "Selecione a opção desejada:"))
        self.btnSimulacoes.setText(_translate("ViewOpcao", "Simulações"))
        self.btnNaoSimular.setText(_translate("ViewOpcao", "Não Simular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewOpcao = QtWidgets.QMainWindow()
    ui = Ui_ViewOpcao()
    ui.setupUi(ViewOpcao)
    ViewOpcao.show()
    sys.exit(app.exec_())
