# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewMetodo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewMetodo(object):
    def setupUi(self, ViewMetodo):
        ViewMetodo.setObjectName("ViewMetodo")
        ViewMetodo.resize(534, 501)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewMetodo.sizePolicy().hasHeightForWidth())
        ViewMetodo.setSizePolicy(sizePolicy)
        ViewMetodo.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        ViewMetodo.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        ViewMetodo.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(ViewMetodo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setObjectName("btnVoltar")
        self.gridLayout.addWidget(self.btnVoltar, 9, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnSelecionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelecionar.setObjectName("btnSelecionar")
        self.gridLayout_3.addWidget(self.btnSelecionar, 0, 1, 1, 1)
        self.leArquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.leArquivo.setObjectName("leArquivo")
        self.gridLayout_3.addWidget(self.leArquivo, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem2)
        self.rbACS = QtWidgets.QRadioButton(self.centralwidget)
        self.rbACS.setMouseTracking(True)
        self.rbACS.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.rbACS.setObjectName("rbACS")
        self.verticalLayout.addWidget(self.rbACS)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem3)
        self.rbACE = QtWidgets.QRadioButton(self.centralwidget)
        self.rbACE.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.rbACE.setObjectName("rbACE")
        self.verticalLayout.addWidget(self.rbACE)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem4)
        self.rbAS = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAS.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.rbAS.setObjectName("rbAS")
        self.verticalLayout.addWidget(self.rbAS)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.btnOK.setObjectName("btnOK")
        self.gridLayout.addWidget(self.btnOK, 9, 4, 1, 1)
        ViewMetodo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ViewMetodo)
        self.statusbar.setObjectName("statusbar")
        ViewMetodo.setStatusBar(self.statusbar)

        self.retranslateUi(ViewMetodo)
        QtCore.QMetaObject.connectSlotsByName(ViewMetodo)

    def retranslateUi(self, ViewMetodo):
        _translate = QtCore.QCoreApplication.translate
        ViewMetodo.setWindowTitle(_translate("ViewMetodo", "SysInventFlor"))
        self.btnVoltar.setText(_translate("ViewMetodo", "Voltar"))
        self.btnSelecionar.setText(_translate("ViewMetodo", "Selecionar"))
        self.label_2.setText(_translate("ViewMetodo", "Arquivo:"))
        self.label.setText(_translate("ViewMetodo", "Escolha o Método de Amostragem:"))
        self.rbACS.setText(_translate("ViewMetodo", "Amostragem Casual Simples"))
        self.rbACE.setText(_translate("ViewMetodo", "Amostragem Casual Estratificada"))
        self.rbAS.setText(_translate("ViewMetodo", "Amostragem Sistemática"))
        self.btnOK.setToolTip(_translate("ViewMetodo", "Precione Ok para selecionar o método desejado"))
        self.btnOK.setText(_translate("ViewMetodo", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewMetodo = QtWidgets.QMainWindow()
    ui = Ui_ViewMetodo()
    ui.setupUi(ViewMetodo)
    ViewMetodo.show()
    sys.exit(app.exec_())
